FROM node:22-slim
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
ENV DATABASE_URL="postgresql://placeholder:placeholder@localhost:5174/placeholder"
RUN npx prisma generate
EXPOSE 3000
CMD [ "node", "src/server.js" ]